### PR TITLE
Add pybind11 include path in setup.py

### PR DESCRIPTION
**Pull request by Kh4L**

### CODE REVIEW

**Comment by Kh4L** [comment]
@cliffwoolley

**Review by matthew-frank — APPROVED** [review]
it turns out the `import pybind11` at line 3 of setup.py fails if pybind isn't already installed, which makes the `install_requires = [ ... 'pybind11>=2.2' ...]` unreachable.  The result is that you need to manually install pybind11 before installing pycocotools.
I think this is okay.  it's not hard to just call `pip install pybind11` before `pip installing` this.  The alternative is to follow the rather ridiculously complicated example at https://github.com/pybind/python_example/blob/5343a8d1e9ba525ab2bd2d5873fd50c69d186855/setup.py#L9 (between lines 9 and 35).  I think this is really a bug in pybind11 (pybind11 refuses to install itself under the same include dir everyone else uses) that we can't really do much about.

**Comment by cliffwoolley** [comment]
@matthew-frank : I can't quite tell whether you're recommending to merge this one or to drop it?

**Comment by matthew-frank** [comment]
please merge.  We have to have some way to work around pybind11 putting its include files whereever it wants to, so we need to #include pybind11 and then call pybind11.get_include().
I don't think it is worth twisting ourselves in circles to figure out how to get setup.py to call pybind11.get_include() before we've told setup.py that pybind11 is a requirement.
We can just pip install pybind11 before we install pycocotools, and then this PR will _work_.  (Whereas without this PR it doesn't matter what we do, building pycocotools fails)

**Comment by matthew-frank** [comment]
I'm not sure why you're not seeing the problem when installing pycocotools into pytorch.  I think it might be because you've already installed pybind11 under conda, so you've somehow forced pybind11 to put its include files somewhere that you already know how to find.
Without this PR, and without conda, then building pycocotools fails _even if_ pybind11 is already installed, because pybind11 puts its include files somewhere different than all other packages put their install files (I forget where it was like /usr/local/include instead of /usr/local/python/include or something), and so the pycocotools build fails when the C compiler tries to include the pybind11 headers.

**Comment by matthew-frank** [comment]
If you're not comfortable with requiring pybind11 to be installed before running setup.py for pycocotools, I can do this hack from the pybind11 example:
https://github.com/pybind/python_example/blob/5343a8d1e9ba525ab2bd2d5873fd50c69d186855/setup.py#L9

**Comment by matthew-frank** [comment]
(I think the pybind11 example is a net lose because it's a super-clever code obfuscation for no apparent real gain)

**Pull request merged**
